### ISSUE TITLE
Сортировка эпизодов в обратном порядке

### ISSUE THREAD

**Issue by sambul13** [mpertsov/movian-lostfilm#4]
Текущий плагин сортирует эпизоды любого сериала в обратном порядке нумерации. В результате невозможен их запуск автоматом из Movian один за другим. Это же видно и на скриншотах в этом репо. У меня такое было также в Коди с плагином LostFilm2. После перехода на плагин LostFilm3 сортировка восстановилась как надо, можно менять в порядке возрастания / убывания. Оба способа нужны.

**Comment by sambul13** [comment]
Посмотрите в OroroTV. Там сортировка показанного списка по возрастающей / убывающей доступна в правом верхнем меню окна. Такая идеально подошла бы для LostFilm плагина. Только открывайте папку Сериалы, а то в Ororo очень большая папка Кино, под 3000, долго парсит.

**Comment by Buksa** [comment]
в ороро лучше не смотреть :) лучше в youtube ;)

**Comment by repa4ok** [comment]
сделано в d76ddb40cd9934a1180c626666a5631b540f8e0f
