### ISSUE TITLE
Авторизация на сайте LostFilm слетает после рестарта ПК

### ISSUE THREAD

**Issue by sambul13** [mpertsov/movian-lostfilm#6]
После рестарта ПК или Movian, плагин снова предлагает авторизоваться на сайте LostFilm после запуска любого фильма. Логин и пароль авторизации теряются при перезагрузке ПК.

**Comment by repa4ok** [comment]
Привет @sambul13 , версия 0.3 или 0.3.3? Слетает именно после ребута или все же после перезапуска мувиана? Версия мувиана? Логин через мэйл или через юзернейм?

**Comment by repa4ok** [comment]
похоже на локальную проблему. на данный момент (0.4.2) не воспроизводится.
